// PLACEHOLDER — album titles, locations, years, and per-photo titles below
// are stand-ins pending real captions from Javi. Structural data (src,
// width, height, order, capture) is real, generated by
// scripts/prepare-images.mjs from photos-master/. Re-run that script and
// update this file by hand whenever photos-master changes.
//
// `place` on every photo is ALSO a placeholder pending Javi filling it in
// by hand — see the Place type below for the exact rules. Do not invent
// cities or coordinates; do not attempt to read GPS from EXIF (almost
// certainly absent from these files).

export type CaptureData = {
  focalLength: string; // e.g. "35mm"
  aperture: string; // e.g. "f/2.8"
  iso: string; // e.g. "ISO 200"
};

export type PlacePrecision = "exact" | "city";

export type Place = {
  city: string;
  country: string;
  // Written by hand — never derived from EXIF. `null` until filled in;
  // every consumer must tolerate that (atlas: omit the mark; caption:
  // "City, Country" alone, which is already what it shows regardless of
  // precision — see below).
  lat: number | null;
  lng: number | null;
  // Governs DISPLAY only, nothing else branches on it:
  //   'exact' — lat/lng are the real spot. May be shown as precise
  //             degree/minute/second coordinates (atlas hover only).
  //   'city'  — Javi doesn't want the exact spot published. lat/lng hold
  //             the CITY CENTROID, not a real location. Must NEVER be
  //             shown as degree/minute/second coordinates — that would
  //             claim a precision the data doesn't have.
  precision: PlacePrecision;
};

export type Album = {
  slug: string;
  title: string;
  location: string;
  year: number;
  order: number;
  cover: string; // src of the photo marked -cover in photos-master
};

export type Photo = {
  src: string; // path under /public/photos, e.g. "/photos/alpes/01.avif"
  width: number;
  height: number;
  title: string;
  album: Album["slug"];
  order: number;
  capture: CaptureData;
  place: Place;
  /** Featured in the landing scatter / carousel. */
  isFeatured?: boolean;
  /** Stable descriptive key, set where a photo has been identified by content. */
  id?: string;
};

// PLACEHOLDER albums — real location/year still needed
export const albums: Album[] = [
  {
    slug: "america",
    title: "América",
    location: "México & Panamá",
    year: 2026,
    order: 1,
    cover: "/photos/america/05.avif",
  },
  {
    slug: "norte",
    title: "Norte",
    location: "España & France",
    year: 2026,
    order: 2,
    cover: "/photos/norte/01.avif",
  },
  {
    slug: "sol",
    title: "Sol",
    location: "España",
    year: 2026,
    order: 3,
    cover: "/photos/sol/07.avif",
  },
  {
    slug: "ny",
    title: "NY",
    location: "New York City, USA",
    year: 2026,
    // Last in the sequence — its "Next Album" footer block links back to
    // the first (getNextAlbum wraps via modulo), closing the loop.
    order: 4,
    cover: "/photos/ny/01.avif",
  },
];

// PLACEHOLDER photos — real titles still needed
export const photos: Photo[] = [
  {
    src: "/photos/america/01.avif",
    width: 2500,
    height: 1875,
    title: "San Miguel Street",
    album: "america",
    order: 1,
    capture: { focalLength: "43mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "San Miguel de Allende", country: "México", lat: 20.91401864718361, lng: -100.74410526628863, precision: "exact" },
    isFeatured: true,
    id: "san-miguel-street",
  },
  {
    src: "/photos/america/02.avif",
    width: 1875,
    height: 2500,
    title: "Paseo por San Miguel",
    album: "america",
    order: 2,
    capture: { focalLength: "47mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "San Miguel de Allende", country: "México", lat: 20.91203419935728, lng: -100.74361528208071, precision: "exact" },
  },
  {
    src: "/photos/america/03.avif",
    width: 2500,
    height: 1875,
    title: "Bougainvillea",
    album: "america",
    order: 3,
    capture: { focalLength: "26mm", aperture: "f/5.6", iso: "ISO 320" },
    place: { city: "San Miguel de Allende", country: "México", lat: 20.90969211733032, lng: -100.74478461955466, precision: "exact" },
    isFeatured: true,
    id: "bougainvillea",
  },
  {
    src: "/photos/america/04.avif",
    width: 2500,
    height: 1668,
    title: "We are the people",
    album: "america",
    order: 4,
    capture: { focalLength: "12mm", aperture: "f/4.5", iso: "ISO 400" },
    place: { city: "Xilitla", country: "México", lat: 21.396740663941568, lng: -98.99934376399437, precision: "city" },
  },
  {
    src: "/photos/america/05.avif",
    width: 2500,
    height: 1875,
    title: "Horses in the Dust",
    album: "america",
    order: 5,
    capture: { focalLength: "14mm", aperture: "f/5", iso: "ISO 100" },
    place: { city: "Puerto Escondido", country: "México", lat: null, lng: null, precision: "city" },
    isFeatured: true,
    id: "horses-dust",
  },
  {
    src: "/photos/america/06.avif",
    width: 2500,
    height: 2336,
    title: "Cowboy",
    album: "america",
    order: 6,
    capture: { focalLength: "28mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "Puerto Escondido", country: "México", lat: null, lng: null, precision: "city" },
    isFeatured: true,
    id: "cowboy-silhouette",
  },
  {
    src: "/photos/america/07.avif",
    width: 1627,
    height: 2500,
    title: "Una tarde con el caballo Orio",
    album: "america",
    order: 7,
    capture: { focalLength: "22mm", aperture: "f/5", iso: "ISO 100" },
    place: { city: "Puerto Escondido", country: "México", lat: null, lng: null, precision: "city" },
  },
  {
    src: "/photos/america/08.avif",
    width: 2500,
    height: 2099,
    title: "End of the World",
    album: "america",
    order: 8,
    capture: { focalLength: "32mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "San Blas", country: "Panamá", lat: null, lng: null, precision: "city" },
    isFeatured: true,
    id: "america-untitled-08",
  },
  {
    src: "/photos/america/09.avif",
    width: 2500,
    height: 1875,
    title: "San Blas Island (Casa de Papel)",
    album: "america",
    order: 9,
    capture: { focalLength: "15mm", aperture: "f/5", iso: "ISO 100" },
    place: { city: "San Blas", country: "Panamá", lat: null, lng: null, precision: "city" },
    isFeatured: true,
    id: "san-blas-island",
  },
  {
    src: "/photos/norte/01.avif",
    width: 1875,
    height: 2500,
    title: "Basque Cliffs",
    album: "norte",
    order: 1,
    capture: { focalLength: "27mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "San Sebastián", country: "España", lat: 43.31961562166937, lng: -2.0333128663450326, precision: "exact" },
    isFeatured: true,
    id: "basque-cliffs",
  },
  {
    src: "/photos/norte/02.avif",
    width: 1627,
    height: 2500,
    title: "Sea Through the Trees",
    album: "norte",
    order: 2,
    capture: { focalLength: "37mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "San Sebastián", country: "España", lat: 43.31864191170185, lng: -2.0310280405645615, precision: "exact" },
    isFeatured: true,
    id: "sea-through-trees",
  },
  {
    src: "/photos/norte/03.avif",
    width: 2500,
    height: 712,
    title: "Waves",
    album: "norte",
    order: 3,
    capture: { focalLength: "10mm", aperture: "f/4.5", iso: "ISO 100" },
    place: { city: "Porto do Son", country: "España", lat: 42.71915015429627, lng: -9.00874854921649, precision: "exact" },
    isFeatured: true,
    id: "waves-panorama",
  },
  {
    src: "/photos/norte/04.avif",
    width: 2500,
    height: 1875,
    title: "Man in the Sea",
    album: "norte",
    order: 4,
    capture: { focalLength: "86mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "Porto do Son", country: "España", lat: 42.71915015429627, lng: -9.00874854921649, precision: "exact" },
    id: "man-in-sea",
  },
  {
    src: "/photos/norte/05.avif",
    width: 1875,
    height: 2500,
    title: "El barco del atardecer",
    album: "norte",
    order: 5,
    capture: { focalLength: "128mm", aperture: "f/6.3", iso: "ISO 160" },
    place: { city: "San Sebastián", country: "España", lat: 43.32655454035025, lng: -1.9866726889973427, precision: "exact" },
  },
  {
    src: "/photos/norte/06.avif",
    width: 2500,
    height: 1875,
    title: "Biarritz Palace",
    album: "norte",
    order: 6,
    capture: { focalLength: "22mm", aperture: "f/5", iso: "ISO 100" },
    place: { city: "Biarritz", country: "Francia", lat: 43.485967583155464,lng: -1.5560944547012845, precision: "exact" },
    isFeatured: true,
    id: "biarritz-palace",
  },
  {
    src: "/photos/norte/07.avif",
    width: 2500,
    height: 1343,
    title: "El mar de Galicia",
    album: "norte",
    order: 7,
    capture: { focalLength: "29mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "A Coruña", country: "España", lat: 43.38735516612886,lng: -8.40604703489836, precision: "exact" },
  },
  {
    src: "/photos/norte/08.avif",
    width: 1406,
    height: 2500,
    title: "Home",
    album: "norte",
    order: 8,
    capture: { focalLength: "12mm", aperture: "f/4.5", iso: "ISO 100" },
    place: { city: "Santiago de Compostela", country: "España", lat: 42.87832948515055,lng: -8.543791924004069, precision: "exact" },
  },
  {
    src: "/photos/ny/01.avif",
    width: 2048,
    height: 1536,
    title: "New York Skyline",
    album: "ny",
    order: 1,
    capture: { focalLength: "24mm", aperture: "f/4.8", iso: "ISO 64" },
    place: { city: "New York City", country: "United States", lat: 40.75930691116888,lng: -73.97946352338468, precision: "exact" },
    isFeatured: true,
    id: "ny-skyline",
  },
  {
    src: "/photos/ny/02.avif",
    width: 1448,
    height: 1930,
    title: "New York Public Library",
    album: "ny",
    order: 2,
    capture: { focalLength: "16mm", aperture: "f/4.2", iso: "ISO 200" },
    place: { city: "New York", country: "United States", lat: 40.75311059665017, lng: -73.98234710852101, precision: "exact" },
    isFeatured: true,
    id: "ny-library",
  },
  {
    src: "/photos/ny/03.avif",
    width: 2048,
    height: 1536,
    title: "Route to SOHO",
    album: "ny",
    order: 3,
    capture: { focalLength: "24mm", aperture: "f/4.8", iso: "ISO 100" },
    place: { city: "New York", country: "United States", lat: 40.75311059665017, lng: -73.98234710852101, precision: "exact" },
  },
  {
    src: "/photos/ny/04.avif",
    width: 2048,
    height: 1536,
    title: "Bridge vibes",
    album: "ny",
    order: 4,
    capture: { focalLength: "16mm", aperture: "f/4.2", iso: "ISO 64" },
    place: { city: "New York", country: "United States", lat: 40.752275142563576, lng: -74.00115585066044, precision: "exact" },
  },
  {
    src: "/photos/ny/05.avif",
    width: 2048,
    height: 1536,
    title: "Vessel",
    album: "ny",
    order: 5,
    capture: { focalLength: "11mm", aperture: "f/3.8", iso: "ISO 64" },
    place: { city: "New York", country: "United States", lat: 40.75361120828311,lng: -74.00204870217928, precision: "exact" },
  },
  {
    src: "/photos/ny/06.avif",
    width: 2048,
    height: 1350,
    title: "Some pizza?",
    album: "ny",
    order: 6,
    capture: { focalLength: "16mm", aperture: "f/4.2", iso: "ISO 200" },
    place: { city: "New York", country: "United States", lat: 40.722089774542546,lng: -73.99635186453946, precision: "exact" },
  },
  {
    src: "/photos/ny/07.avif",
    width: 2048,
    height: 1536,
    title: "Statue of Liberty",
    album: "ny",
    order: 7,
    capture: { focalLength: "28mm", aperture: "f/5.3", iso: "ISO 64" },
    place: { city: "New York", country: "United States", lat: 40.688683004779705,lng: -74.04482308846788, precision: "exact" },
  },
  {
    src: "/photos/sol/01.avif",
    width: 1875,
    height: 2500,
    title: "Dune in San Sebastián",
    album: "sol",
    order: 1,
    capture: { focalLength: "44mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "San Sebastián", country: "España", lat: 43.326681795284905,lng: -1.9871325760639986,  precision: "exact" },
  },
  {
    src: "/photos/sol/02.avif",
    width: 1875,
    height: 2500,
    title: "Tarde con amigos",
    album: "sol",
    order: 2,
    capture: { focalLength: "35mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "San Sebastián", country: "España", lat: 43.31961562166937, lng: -2.0333128663450326, precision: "exact" },
  },
  {
    src: "/photos/sol/03.avif",
    width: 1875,
    height: 2500,
    title: "Red Sun, Boat",
    album: "sol",
    order: 3,
    capture: { focalLength: "105mm", aperture: "f/6.3", iso: "ISO 100" },
    place: { city: "San Sebastián", country: "España", lat: 43.326681795284905,lng: -1.9871325760639986, precision: "exact" },
    isFeatured: true,
    id: "red-sun-boat",
  },
  {
    src: "/photos/sol/04.avif",
    width: 1406,
    height: 2500,
    title: "PreEclipse",
    album: "sol",
    order: 4,
    capture: { focalLength: "34mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "Villaquirán de la puebla", country: "España", lat: 42.27533681781175, lng:-4.104323261215063, precision: "exact" },
  },
  {
    src: "/photos/sol/05.avif",
    width: 2500,
    height: 3333,
    title: "Cristo Silhouette",
    album: "sol",
    order: 5,
    capture: { focalLength: "54mm", aperture: "f/5.6", iso: "ISO 100" },
    place: { city: "San Sebastián", country: "España", lat: 43.320672031162296, lng:-1.9769729544059893, precision: "exact" },
    isFeatured: true,
    id: "cristo-silhouette",
  },
  {
    src: "/photos/sol/06.avif",
    width: 1875,
    height: 2500,
    title: "Luna de Sol",
    album: "sol",
    order: 6,
    capture: { focalLength: "94mm", aperture: "f/6.3", iso: "ISO 800" },
    place: { city: "Villaquirán de la puebla", country: "España", lat: 42.27533681781175, lng:-4.104323261215063, precision: "exact" },
  },
  {
    src: "/photos/sol/07.avif",
    width: 1875,
    height: 2500,
    title: "Total Eclipse",
    album: "sol",
    order: 7,
    capture: { focalLength: "88mm", aperture: "f/5.6", iso: "ISO 800" },
    place: { city: "Villaquirán de la puebla", country: "España", lat: 42.27533681781175, lng:-4.104323261215063, precision: "exact" },
    isFeatured: true,
    id: "eclipse-totality",
  },
];

export function getAlbumBySlug(slug: string): Album | undefined {
  return albums.find((album) => album.slug === slug);
}

export function getPhotosByAlbum(slug: string): Photo[] {
  return photos
    .filter((photo) => photo.album === slug)
    .sort((a, b) => a.order - b.order);
}

export function getOrderedAlbums(): Album[] {
  return [...albums].sort((a, b) => a.order - b.order);
}

export function getFeaturedPhotos(): Photo[] {
  return photos.filter((photo) => photo.isFeatured);
}

/** Next album by order, wrapping around to the first. */
export function getNextAlbum(slug: string): Album {
  const ordered = getOrderedAlbums();
  const index = ordered.findIndex((album) => album.slug === slug);
  return ordered[(index + 1) % ordered.length];
}

/**
 * `count` albums on each side of `slug`, wrapping circularly — used for the
 * carousel's slivers. With fewer albums than `count * 2`, neighbors repeat.
 */
export function getCarouselNeighbors(slug: string, count: number) {
  const ordered = getOrderedAlbums();
  const index = ordered.findIndex((album) => album.slug === slug);
  const left: Album[] = [];
  const right: Album[] = [];
  for (let i = 1; i <= count; i++) {
    left.unshift(ordered[(index - i + ordered.length * count) % ordered.length]);
    right.push(ordered[(index + i) % ordered.length]);
  }
  return { left, right };
}
