// PLACEHOLDER — album titles, locations, years, and per-photo titles below
// are stand-ins pending real captions from Javi. Structural data (src,
// width, height, order, capture) is real, generated by
// scripts/prepare-images.mjs from photos-master/. Re-run that script and
// update this file by hand whenever photos-master changes.

export type CaptureData = {
  focalLength: string; // e.g. "35mm"
  aperture: string; // e.g. "f/2.8"
  iso: string; // e.g. "ISO 200"
};

export type Album = {
  slug: string;
  title: string;
  location: string;
  year: number;
  order: number;
  cover: string; // src of the photo marked -cover in photos-master
};

export type Photo = {
  src: string; // path under /public/photos, e.g. "/photos/alpes/01.avif"
  width: number;
  height: number;
  title: string;
  album: Album["slug"];
  order: number;
  capture: CaptureData;
  /** Featured in the landing scatter / carousel. */
  isFeatured?: boolean;
};

// PLACEHOLDER albums — real location/year still needed
export const albums: Album[] = [
  {
    slug: "america",
    title: "América",
    location: "TBD",
    year: 2026,
    order: 1,
    cover: "/photos/america/05.avif",
  },
  {
    slug: "norte",
    title: "Norte",
    location: "TBD",
    year: 2026,
    order: 2,
    cover: "/photos/norte/01.avif",
  },
  {
    slug: "ny",
    title: "NY",
    location: "TBD",
    year: 2026,
    order: 3,
    cover: "/photos/ny/01.avif",
  },
  {
    slug: "sol",
    title: "Sol",
    location: "TBD",
    year: 2026,
    order: 4,
    cover: "/photos/sol/07.avif",
  },
];

// PLACEHOLDER photos — real titles still needed
export const photos: Photo[] = [
  {
    src: "/photos/america/01.avif",
    width: 2500,
    height: 1875,
    title: "Untitled — 01",
    album: "america",
    order: 1,
    capture: { focalLength: "43mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/america/02.avif",
    width: 1875,
    height: 2500,
    title: "Untitled — 02",
    album: "america",
    order: 2,
    capture: { focalLength: "47mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/america/03.avif",
    width: 2500,
    height: 1875,
    title: "Untitled — 03",
    album: "america",
    order: 3,
    capture: { focalLength: "26mm", aperture: "f/5.6", iso: "ISO 320" },
  },
  {
    src: "/photos/america/04.avif",
    width: 2500,
    height: 1668,
    title: "Untitled — 04",
    album: "america",
    order: 4,
    capture: { focalLength: "12mm", aperture: "f/4.5", iso: "ISO 400" },
  },
  {
    src: "/photos/america/05.avif",
    width: 2500,
    height: 1875,
    title: "Untitled — 05",
    album: "america",
    order: 5,
    capture: { focalLength: "14mm", aperture: "f/5", iso: "ISO 100" },
    isFeatured: true,
  },
  {
    src: "/photos/america/06.avif",
    width: 2500,
    height: 2336,
    title: "Untitled — 06",
    album: "america",
    order: 6,
    capture: { focalLength: "28mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/america/07.avif",
    width: 1627,
    height: 2500,
    title: "Untitled — 07",
    album: "america",
    order: 7,
    capture: { focalLength: "22mm", aperture: "f/5", iso: "ISO 100" },
  },
  {
    src: "/photos/america/08.avif",
    width: 2500,
    height: 2099,
    title: "Untitled — 08",
    album: "america",
    order: 8,
    capture: { focalLength: "32mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/america/09.avif",
    width: 2500,
    height: 1875,
    title: "Untitled — 09",
    album: "america",
    order: 9,
    capture: { focalLength: "15mm", aperture: "f/5", iso: "ISO 100" },
  },
  {
    src: "/photos/norte/01.avif",
    width: 1875,
    height: 2500,
    title: "Untitled — 01",
    album: "norte",
    order: 1,
    capture: { focalLength: "27mm", aperture: "f/5.6", iso: "ISO 100" },
    isFeatured: true,
  },
  {
    src: "/photos/norte/02.avif",
    width: 1627,
    height: 2500,
    title: "Untitled — 02",
    album: "norte",
    order: 2,
    capture: { focalLength: "37mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/norte/03.avif",
    width: 2500,
    height: 712,
    title: "Untitled — 03",
    album: "norte",
    order: 3,
    capture: { focalLength: "10mm", aperture: "f/4.5", iso: "ISO 100" },
  },
  {
    src: "/photos/norte/04.avif",
    width: 2500,
    height: 1875,
    title: "Untitled — 04",
    album: "norte",
    order: 4,
    capture: { focalLength: "86mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/norte/05.avif",
    width: 1875,
    height: 2500,
    title: "Untitled — 05",
    album: "norte",
    order: 5,
    capture: { focalLength: "128mm", aperture: "f/6.3", iso: "ISO 160" },
  },
  {
    src: "/photos/norte/06.avif",
    width: 2500,
    height: 1875,
    title: "Untitled — 06",
    album: "norte",
    order: 6,
    capture: { focalLength: "22mm", aperture: "f/5", iso: "ISO 100" },
  },
  {
    src: "/photos/norte/07.avif",
    width: 2500,
    height: 1343,
    title: "Untitled — 07",
    album: "norte",
    order: 7,
    capture: { focalLength: "29mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/norte/08.avif",
    width: 1406,
    height: 2500,
    title: "Untitled — 08",
    album: "norte",
    order: 8,
    capture: { focalLength: "12mm", aperture: "f/4.5", iso: "ISO 100" },
  },
  {
    src: "/photos/ny/01.avif",
    width: 2048,
    height: 1536,
    title: "Untitled — 01",
    album: "ny",
    order: 1,
    capture: { focalLength: "24mm", aperture: "f/4.8", iso: "ISO 64" },
    isFeatured: true,
  },
  {
    src: "/photos/ny/02.avif",
    width: 1448,
    height: 1930,
    title: "Untitled — 02",
    album: "ny",
    order: 2,
    capture: { focalLength: "16mm", aperture: "f/4.2", iso: "ISO 200" },
  },
  {
    src: "/photos/ny/03.avif",
    width: 2048,
    height: 1536,
    title: "Untitled — 03",
    album: "ny",
    order: 3,
    capture: { focalLength: "24mm", aperture: "f/4.8", iso: "ISO 100" },
  },
  {
    src: "/photos/ny/04.avif",
    width: 2048,
    height: 1536,
    title: "Untitled — 04",
    album: "ny",
    order: 4,
    capture: { focalLength: "16mm", aperture: "f/4.2", iso: "ISO 64" },
  },
  {
    src: "/photos/ny/05.avif",
    width: 2048,
    height: 1536,
    title: "Untitled — 05",
    album: "ny",
    order: 5,
    capture: { focalLength: "11mm", aperture: "f/3.8", iso: "ISO 64" },
  },
  {
    src: "/photos/ny/06.avif",
    width: 2048,
    height: 1350,
    title: "Untitled — 06",
    album: "ny",
    order: 6,
    capture: { focalLength: "16mm", aperture: "f/4.2", iso: "ISO 200" },
  },
  {
    src: "/photos/ny/07.avif",
    width: 2048,
    height: 1536,
    title: "Untitled — 07",
    album: "ny",
    order: 7,
    capture: { focalLength: "28mm", aperture: "f/5.3", iso: "ISO 64" },
  },
  {
    src: "/photos/sol/01.avif",
    width: 1875,
    height: 2500,
    title: "Untitled — 01",
    album: "sol",
    order: 1,
    capture: { focalLength: "44mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/sol/02.avif",
    width: 1875,
    height: 2500,
    title: "Untitled — 02",
    album: "sol",
    order: 2,
    capture: { focalLength: "35mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/sol/03.avif",
    width: 1875,
    height: 2500,
    title: "Untitled — 03",
    album: "sol",
    order: 3,
    capture: { focalLength: "105mm", aperture: "f/6.3", iso: "ISO 100" },
  },
  {
    src: "/photos/sol/04.avif",
    width: 1406,
    height: 2500,
    title: "Untitled — 04",
    album: "sol",
    order: 4,
    capture: { focalLength: "34mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/sol/05.avif",
    width: 2500,
    height: 3333,
    title: "Untitled — 05",
    album: "sol",
    order: 5,
    capture: { focalLength: "54mm", aperture: "f/5.6", iso: "ISO 100" },
  },
  {
    src: "/photos/sol/06.avif",
    width: 1875,
    height: 2500,
    title: "Untitled — 06",
    album: "sol",
    order: 6,
    capture: { focalLength: "94mm", aperture: "f/6.3", iso: "ISO 800" },
  },
  {
    src: "/photos/sol/07.avif",
    width: 1875,
    height: 2500,
    title: "Untitled — 07",
    album: "sol",
    order: 7,
    capture: { focalLength: "88mm", aperture: "f/5.6", iso: "ISO 800" },
    isFeatured: true,
  },
];

export function getAlbumBySlug(slug: string): Album | undefined {
  return albums.find((album) => album.slug === slug);
}

export function getPhotosByAlbum(slug: string): Photo[] {
  return photos
    .filter((photo) => photo.album === slug)
    .sort((a, b) => a.order - b.order);
}
